version: '3'

services:
  postgres:
    image: postgres:15
    container_name: database-postgres
    ports:
        - "5433:5432"
    environment:
      POSTGRES_USER: yaidercc
      POSTGRES_PASSWORD: yaidercc123
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - api

  backend:
    depends_on:
      - postgres
    build:
      context: ./APP-NODE
      dockerfile: Dockerfile
    container_name: backend-node
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER:  yaidercc
      DB_PASSWORD:  yaidercc123
      DB_HOST: postgres
      SECRETKEY: ${SECRETKEY}
    networks:
      - api

  frontend:
    depends_on:
      - backend
    build:
      context: ./APP-REACT
      dockerfile: Dockerfile
    container_name: frontend-react
    ports:
      - "5173:80"
    networks:
      - api
    
volumes:
  postgres_data:
    driver: local
networks:
  api:
    driver: bridge